from tkinter import*
from tkinter import messagebox
new=Tk()
new.title("welcome")
new.config(bg="light blue")
new.geometry("400x400")
def third():
    dd1=Frame(new,width=600,height=600,bg="red")
    dd1.place(x=0,y=0)
    a=Label(new,text="third page",font=("century",18,"bold"),bg="black",fg="white")
    a.place(x=150,y=50)
    c=Button(new,text="prevpage",font=("century",18,"bold"),bg="white",fg="black",height=2,width=10,bd=10,command=nextpage)
    c.place(x=150,y=350)
def nextpage():
    ##messagebox.askyesno("confirm","Are you sure")
    ##messagebox.showinfo("done","Successfully ID Created")
    ##messagebox.showerror("error","not found")
    dd=Frame(new,width=600,height=600,bg="white")
    dd.place(x=0,y=0)
    a=Label(new,text="welcome Admin",font=("century",18,"bold"),bg="black",fg="yellow")
    a.place(x=100,y=50)
    b=Button(new,text="prevpage",font=("century",18,"bold"),bg="white",fg="black",height=2,width=10,bd=10,command=third)
    b.place(x=150,y=350)
a=Label(new,text="welcome home harry",font=("century",18,"bold"),bg=("black"),fg="white")
a.place(x=500,y=150)
e=Label(new,text="text here",font=("century",18,"bold"),bg=("black"),fg="white")
e.place(x=350,y=200)
b=Entry(new,font=("century",18,"italic"))
b.place(x=500,y=200)
c=Button(new,text="tap",font=("century",16,"bold"),bg="black",fg="white",height=2,width=7,bd=5,command=nextpage)
c.place(x=150,y=250)
Radiobutton(new,text="op1",value="op1").place(x=200,y=350)
Radiobutton(new,text="op2",value="op2").place(x=200,y=370)
Checkbutton(new,text="op1").place(x=200,y=390)
Checkbutton(new,text="op2").place(x=200,y=410)

new.mainloop()
